#!/usr/bin/env bash
# Full headless verification suite — exit 0 when all suites pass.
set -uo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

# Smoke-speed world bake: production defaults to full playable map; suite uses radius-2.
export CRYSTALSTORM_BAKE_RADIUS="${CRYSTALSTORM_BAKE_RADIUS:-2}"
export CRYSTALSTORM_FULL_WORLD_BAKE="${CRYSTALSTORM_FULL_WORLD_BAKE:-0}"
export CRYSTALSTORM_BAKE_ON_NEW="${CRYSTALSTORM_BAKE_ON_NEW:-0}"

SUITES=(
	"res://scripts/verify_stability_perf.gd"
	"res://scripts/verify_game_visuals.gd"
	"res://scripts/verify_visual_pipeline.gd"
	"res://scripts/verify_visual_boot_order.gd"
	"res://scripts/verify_visual_texture_binding.gd"
	"res://scripts/verify_bootstrap_no_deadlock.gd"
	"res://scripts/verify_composition_root.gd"
	"res://scripts/verify_composition_boot.gd"
	"res://scripts/verify_spatial_query.gd"
	"res://scripts/verify_crystal_simulation_split.gd"
	"res://scripts/verify_entity_spawn_order.gd"
	"res://scripts/verify_chunk_bootstrap.gd"
	"res://scripts/verify_player_jump.gd"
	"res://scripts/verify_jump_while_moving.gd"
	"res://scripts/verify_terrain_dig.gd"
	"res://scripts/verify_terrain_build.gd"
	"res://scripts/verify_terrain_feel.gd"
	"res://scripts/verify_terrain_loop_complete.gd"
	"res://scripts/verify_terrain_input_single.gd"
	"res://scripts/verify_crystal_mesh_floor.gd"
	"res://scripts/verify_building_sprint.gd"
	"res://scripts/verify_gate_bridge_visual_identity.gd"
	"res://scripts/verify_wood_wall_authored.gd"
	"res://scripts/verify_stone_wall_authored.gd"
	"res://scripts/verify_gate_authored.gd"
	"res://scripts/verify_bridge_authored.gd"
	"res://scripts/verify_ruin_pillar_authored.gd"
	"res://scripts/verify_town_hall_authored.gd"
	"res://scripts/verify_world_borders.gd"
	"res://scripts/verify_voxel_fluid_engine.gd"
	"res://scripts/verify_water_sprint.gd"
	"res://scripts/verify_water_active_region.gd"
	"res://scripts/verify_building_orientation.gd"
	"res://scripts/verify_edit_mesh_stream.gd"
	"res://scripts/verify_ramp_resident_mesh.gd"
	"res://scripts/verify_macro_layer_grid.gd"
	"res://scripts/verify_micro_layer_grid.gd"
	"res://scripts/verify_micro_column_mesh_parity.gd"
	"res://scripts/verify_macro_micro_save_migrate.gd"
	"res://scripts/verify_dug_strata_no_cap.gd"
	"res://scripts/verify_chunk_surface_zero.gd"
	"res://scripts/verify_chunk_atlas.gd"
	"res://scripts/verify_ramp_concave.gd"
	"res://scripts/verify_ramp_corner.gd"
	"res://scripts/verify_ramp_landing.gd"
	"res://scripts/verify_ramp_cell_exclusive.gd"
	"res://scripts/verify_ramp_slope.gd"
	"res://scripts/verify_target_highlight.gd"
	"res://scripts/verify_target_facing.gd"
	"res://scripts/verify_camera_continuous_yaw.gd"
	"res://scripts/verify_camera_angle_validation.gd"
	"res://scripts/verify_main_runtime_health.gd"
	"res://scripts/verify_manual_checklist_corroboration.gd"
	"res://scripts/verify_perf_preset_boot.gd"
	"res://scripts/verify_weapon_attack.gd"
	"res://scripts/verify_combat_entity_hit.gd"
	"res://scripts/verify_combat_crystal_damage.gd"
	"res://scripts/verify_item_icons.gd"
	"res://scripts/verify_entity_nav_perf.gd"
	"res://scripts/verify_visual_perf.gd"
	"res://scripts/verify_crystal_spread_limits.gd"
	"res://scripts/verify_crystal_flow_mechanics.gd"
	"res://scripts/verify_crystal_live_spread.gd"
	"res://scripts/verify_full_game_loop.gd"
	"res://scripts/verify_playable_loop.gd"
	"res://scripts/verify_living_world.gd"
	"res://scripts/verify_town_rally.gd"
	"res://scripts/verify_early_survival.gd"
	"res://scripts/verify_frame_budget.gd"
	"res://scripts/verify_ruin_expedition.gd"
	"res://scripts/verify_crystal_terrain_routing.gd"
	"res://scripts/verify_crystal_grid_align.gd"
	"res://scripts/verify_crystal_renderer_structural.gd"
	"res://scripts/verify_entity_death_signal.gd"
	"res://scripts/verify_loaded_chunk_bounds.gd"
	"res://scripts/verify_topographical_map.gd"
	"res://scripts/verify_vegetation_perf.gd"
	"res://scripts/verify_main_thread_relief.gd"
	"res://scripts/verify_combat_parse.gd"
	"res://scripts/verify_spawn_goal.gd"
	"res://scripts/verify_maze_phase.gd"
	"res://scripts/verify_maze_pressure_assault.gd"
	"res://scripts/verify_crystal_frontier_readability.gd"
	"res://scripts/verify_ruin_centers.gd"
	"res://scripts/verify_save_terrain.gd"
	"res://scripts/verify_save_architecture.gd"
	"res://scripts/verify_save_transaction.gd"
	"res://scripts/verify_world_state.gd"
	"res://scripts/verify_world_state_stale_worker.gd"
	"res://scripts/verify_chunk_pipeline.gd"
	"res://scripts/verify_world_bake.gd"
	"res://scripts/verify_deferred_world_bake.gd"
	"res://scripts/verify_bake_one_chunk_parity.gd"
	"res://scripts/verify_deferred_bake_workers.gd"
	"res://scripts/verify_world_frontend.gd"
	"res://scripts/verify_world_frontend_flow.gd"
	"res://scripts/verify_live_world_inspector.gd"
	"res://scripts/verify_visual_collision_contract.gd"
	"res://scripts/verify_start_region_gate.gd"
	"res://scripts/verify_pause_debug_ui.gd"
	"res://scripts/verify_quality_preset_distance.gd"
	"res://scripts/verify_dev_ui_live.gd"
	"res://scripts/autonomous_gameplay_audit.gd"
	"res://scripts/verify_mesh_plan_cache.gd"
	"res://scripts/verify_full_world_bake.gd"
	"res://scripts/verify_streamed_world_bake.gd"
	"res://scripts/verify_chunk_unload_ownership.gd"
	"res://scripts/verify_save_slot_main.gd"
	"res://scripts/verify_evidence_split.gd"
	"res://scripts/verify_manual_pristine_after_probe.gd"
	"res://scripts/verify_display_probe_contract.gd"
	"res://scripts/verify_display_session_log.gd"
	"res://scripts/verify_smoke_contract.gd"
	"res://scripts/verify_smoke_quit_path.gd"
	"res://scripts/verify_smoke_gameplay.gd"
	"res://scripts/verify_dev_chat.gd"
)

# Main-scene probes SIGKILL on OK to avoid Godot teardown abort(134); match terminal marker not exit code.
declare -A ABRUPT_OK_MARKER=(
	["res://scripts/verify_bootstrap_no_deadlock.gd"]="All bootstrap deadlock tests OK"
	["res://scripts/verify_main_runtime_health.gd"]="All main runtime health tests OK"
	["res://scripts/verify_crystal_live_spread.gd"]="All crystal live spread tests OK"
	["res://scripts/verify_full_game_loop.gd"]="All full game loop tests OK"
	["res://scripts/verify_playable_loop.gd"]="All playable loop tests OK"
	["res://scripts/verify_living_world.gd"]="All living world tests OK"
	["res://scripts/verify_town_rally.gd"]="All town rally tests OK"
	["res://scripts/verify_early_survival.gd"]="All early survival tests OK"
	["res://scripts/verify_frame_budget.gd"]="All frame budget tests OK"
	["res://scripts/verify_ruin_expedition.gd"]="All ruin expedition tests OK"
	["res://scripts/verify_world_bake.gd"]="All world bake tests OK"
	["res://scripts/verify_deferred_world_bake.gd"]="All deferred world bake tests OK"
	["res://scripts/verify_bake_one_chunk_parity.gd"]="All bake one-chunk parity tests OK"
	["res://scripts/verify_deferred_bake_workers.gd"]="All deferred bake worker tests OK"
	["res://scripts/verify_world_frontend.gd"]="All world frontend tests OK"
	["res://scripts/verify_world_frontend_flow.gd"]="All world frontend flow tests OK"
	["res://scripts/verify_live_world_inspector.gd"]="All live world inspector tests OK"
	["res://scripts/verify_visual_collision_contract.gd"]="All visual collision contract tests OK"
	["res://scripts/verify_start_region_gate.gd"]="All start region gate tests OK"
	["res://scripts/verify_pause_debug_ui.gd"]="All pause/debug UI tests OK"
	["res://scripts/verify_dev_ui_live.gd"]="All dev UI live tests OK"
	["res://scripts/autonomous_gameplay_audit.gd"]="All autonomous gameplay audit OK"
	["res://scripts/verify_mesh_plan_cache.gd"]="All mesh plan cache tests OK"
	["res://scripts/verify_full_world_bake.gd"]="All full world bake tests OK"
	["res://scripts/verify_streamed_world_bake.gd"]="All streamed world bake tests OK"
	["res://scripts/verify_chunk_unload_ownership.gd"]="All chunk unload ownership tests OK"

	["res://scripts/verify_manual_checklist_corroboration.gd"]="Manual checklist corroboration OK"
	["res://scripts/verify_macro_layer_grid.gd"]="All macro layer grid tests OK"
	["res://scripts/verify_micro_layer_grid.gd"]="All micro layer grid tests OK"
	["res://scripts/verify_micro_column_mesh_parity.gd"]="All micro column mesh parity tests OK"
	["res://scripts/verify_macro_micro_save_migrate.gd"]="All macro/micro save migrate tests OK"
	["res://scripts/verify_terrain_feel.gd"]="All terrain feel tests OK"
	["res://scripts/verify_terrain_loop_complete.gd"]="All terrain loop complete tests OK"
	["res://scripts/verify_terrain_input_single.gd"]="All terrain input single tests OK"
	["res://scripts/verify_crystal_mesh_floor.gd"]="All crystal mesh floor tests OK"
	["res://scripts/verify_building_sprint.gd"]="All building sprint tests OK"
	["res://scripts/verify_gate_bridge_visual_identity.gd"]="All gate/bridge visual identity tests OK"
	["res://scripts/verify_wood_wall_authored.gd"]="All wood_wall authored pipeline tests OK"
	["res://scripts/verify_stone_wall_authored.gd"]="All stone_wall authored pipeline tests OK"
	["res://scripts/verify_gate_authored.gd"]="All gate authored pipeline tests OK"
	["res://scripts/verify_bridge_authored.gd"]="All bridge authored pipeline tests OK"
	["res://scripts/verify_ruin_pillar_authored.gd"]="All ruin_pillar authored pipeline tests OK"
	["res://scripts/verify_town_hall_authored.gd"]="All town_hall authored pipeline tests OK"
	["res://scripts/verify_world_borders.gd"]="All world border tests OK"
	["res://scripts/verify_maze_pressure_assault.gd"]="All maze pressure assault loop tests OK"
	["res://scripts/verify_crystal_frontier_readability.gd"]="All crystal frontier readability tests OK"
	["res://scripts/verify_voxel_fluid_engine.gd"]="All voxel fluid engine tests OK"
	["res://scripts/verify_water_sprint.gd"]="All water sprint tests OK"
	["res://scripts/verify_water_active_region.gd"]="All water active-region tests OK"
	["res://scripts/verify_building_orientation.gd"]="All building orientation tests OK"
	["res://scripts/verify_camera_continuous_yaw.gd"]="All camera continuous yaw tests OK"
	["res://scripts/verify_camera_angle_validation.gd"]="All camera angle validation tests OK"
	["res://scripts/verify_edit_mesh_stream.gd"]="All edit mesh stream tests OK"
	["res://scripts/verify_ramp_resident_mesh.gd"]="All ramp resident mesh tests OK"
	["res://scripts/verify_save_transaction.gd"]="All save transaction tests OK"
	["res://scripts/verify_composition_boot.gd"]="All composition boot tests OK"
)

FAILED=0
for path in "${SUITES[@]}"; do
	echo ">>> Running ${path}"
	if [[ -n "${ABRUPT_OK_MARKER[$path]:-}" ]]; then
		out="$(env CRYSTALSTORM_PROBE_ABRUPT_EXIT=1 godot --headless --path "$ROOT" -s "$path" 2>&1 || true)"
		if grep -qF "${ABRUPT_OK_MARKER[$path]}" <<<"$out"; then
			echo "    OK"
		else
			echo "    FAIL (missing OK marker)"
			printf '%s\n' "$out" | tail -8
			FAILED=1
		fi
	elif godot --headless --path "$ROOT" -s "$path" >/dev/null 2>&1; then
		echo "    OK"
	else
		echo "    FAIL (exit $?)"
		FAILED=1
	fi
done

if [[ $FAILED -eq 0 ]]; then
	echo ""
	echo "=== ALL VERIFY SUITES PASSED (${#SUITES[@]}) ==="
	exit 0
fi
exit 1